config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :boards do
    resources :messages, :controller => 'board_messages'
  end

  root 'boards#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
	
	belongs_to :category
	belongs_to :user
	has_many :messages

end

app/models/category.rb
class Category < ActiveRecord::Base

	# TODO: add validation
	has_many :boards
	
end

app/models/message.rb
class Message < ActiveRecord::Base

	# TODO: add validation
	belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

end

app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController

	before_action :find_board

	def index
		@messages = @board.messages
	end

	def show
		@message = @board.messages.find( params[:id] )
	end

	def new
		@message = @board.messages.build
	end

	def create
		@message = @board.messages.build( message_params )
		if @message.save
			redirect_to board_path( @board )
		else
			render :action => :new
		end
	end

	def edit
		@message = @board.messages.find( params[:id] )
	end

	def update
		@message = @board.messages.find( params[:id] )

		if @message.update
			redirect_to board_path( @board )
		else
			render :action => 'edit'
		end
	end

	def destroy
		@message = @board.messages.find( params[:id] )
		@message.destroy

		redirect_to board_messages_url( @board )
	end

	protected

	def find_board
		@board = Board.find( params[:board_id] )
	end

	def message_params
  	params.require( :message ).permit( :word )
	end
	
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	
	before_action :set_board, :only => [ :show, :edit, :update, :destroy]

	def index
		@boards = Board.page( params[:page] )
	end

	def new
		@board = Board.new
	end

	def create
		@board = Board.new( board_params )
		@board.user = current_user
		
		if @board.save
			flash[:notice] = "Board was successfully created"
			redirect_to boards_url
		else
			render :action => :new
		end
	end

	def show
		@messages = @board.messages.all
		@message = Message.new
	end

	def edit
	end

	def update
		if @board.update(board_params)
			redirect_to board_url(@board)
			flash[:notice] = "board was successfully updated"
		else
			render :action => :edit
		end
	end

	def destroy
		@board.destroy
		flash[:notice] = "board was successfully destroyed"
		redirect_to boards_url
	end

	private

	def board_params
		params.require(:board).permit(:title, :content)
	end

	def set_board
		@board = Board.find(params[:id])
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/boards/index.html.erb
<table>
	<tr>
		<td><h2>Title</h2></td>
		<td><h2>Time</h2></td>
	</tr>

	<% @boards.each do |board| %>
	<tr>
		<td><%= link_to board.title, board_path(board) %> </td>
		<td> <%= board.created_at %> </td>
	</tr>
	<% end %>

</table>

</br></br>
<div> <%= link_to 'New Article',new_board_path %> </div>

app/views/boards/new.html.erb
<%= form_for @board, :url => :boards do |f| %>

	<% if @board.errors.any? %>
      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<div>
	<%= f.collection_select( :category_id, Category.all, :id, :name) %>
</div>

<div >
<%= f.label :title, "Title" %>
<%= f.text_field :title %>
</div>

<div >
<%= f.label :content, "Content" %>
<%= f.text_area :content %>
</div>

    <%= f.submit "Create" %>

<% end %>

app/views/boards/show.html.erb
<h4>Title</h4>
<%=	@board.title %>

<h4>Content</h4>
<%= simple_format( @board.content ) %>

<p><%= link_to 'back_to_index', boards_path %> </p>

<h4>留言：</h4>

<ul>
	<% @messages.each do |message| %>
	<li>
		<%= message.word %>
	</li>
	<% end %>

</ul>

<%= form_for @message, :url => board_messages_path( @board ) do |f| %>

<% if @message.errors.any? %>
<ul>
	<% @message.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<div >
	<%= f.label :word, "Comment" %>
	<%= f.text_field :word %>

</div>
<%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suply</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>鍵盤救災</h1>

<% if current_user %>
	<div>你好,<%= current_user.username %></div> 
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('修改密碼', edit_registration_path(:user)) %>
<% else %>
  <%= link_to('註冊', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
<% end %>

<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>


<% if notice %>
	<p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>